name: 'Test action function'
on: push

jobs:

  build_push_delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mickeyli789/anothertest-app:tester
      
      # - name: Delete Image
      #   uses: mhl787156/dockerhub-delete-tag-action@main
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     organisation: ${{ secrets.DOCKERHUB_USERNAME }}
      #     image: mickeyli789/anothertest-app
      #     tag: tester
          

